-- Ads Operations Integrity - Per-store D1
-- Migration 0002: queryable Amazon Ads daily facts.

-- Common operational metrics are queryable columns. Less common Amazon metrics remain preserved in metrics_json and raw R2 objects.
CREATE TABLE campaign_daily (
  profile_id TEXT NOT NULL,
  report_date TEXT NOT NULL,
  ad_product TEXT NOT NULL,
  campaign_id TEXT NOT NULL,
  impressions INTEGER NOT NULL DEFAULT 0 CHECK (impressions >= 0),
  clicks INTEGER NOT NULL DEFAULT 0 CHECK (clicks >= 0),
  cost_micros INTEGER NOT NULL DEFAULT 0 CHECK (cost_micros >= 0),
  purchases INTEGER NOT NULL DEFAULT 0 CHECK (purchases >= 0),
  units_sold INTEGER NOT NULL DEFAULT 0 CHECK (units_sold >= 0),
  sales_micros INTEGER NOT NULL DEFAULT 0 CHECK (sales_micros >= 0),
  purchases_same_sku INTEGER CHECK (purchases_same_sku IS NULL OR purchases_same_sku >= 0),
  units_sold_same_sku INTEGER CHECK (units_sold_same_sku IS NULL OR units_sold_same_sku >= 0),
  sales_same_sku_micros INTEGER CHECK (sales_same_sku_micros IS NULL OR sales_same_sku_micros >= 0),
  metrics_json TEXT,
  source_report_job_id TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (profile_id, report_date, ad_product, campaign_id),
  FOREIGN KEY (profile_id) REFERENCES amazon_profiles(profile_id) ON DELETE RESTRICT,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE RESTRICT,
  FOREIGN KEY (source_report_job_id) REFERENCES report_jobs(job_id) ON DELETE SET NULL
);

CREATE TABLE ad_group_daily (
  profile_id TEXT NOT NULL,
  report_date TEXT NOT NULL,
  ad_product TEXT NOT NULL,
  campaign_id TEXT NOT NULL,
  ad_group_id TEXT NOT NULL,
  impressions INTEGER NOT NULL DEFAULT 0 CHECK (impressions >= 0),
  clicks INTEGER NOT NULL DEFAULT 0 CHECK (clicks >= 0),
  cost_micros INTEGER NOT NULL DEFAULT 0 CHECK (cost_micros >= 0),
  purchases INTEGER NOT NULL DEFAULT 0 CHECK (purchases >= 0),
  units_sold INTEGER NOT NULL DEFAULT 0 CHECK (units_sold >= 0),
  sales_micros INTEGER NOT NULL DEFAULT 0 CHECK (sales_micros >= 0),
  metrics_json TEXT,
  source_report_job_id TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (profile_id, report_date, ad_product, ad_group_id),
  FOREIGN KEY (profile_id) REFERENCES amazon_profiles(profile_id) ON DELETE RESTRICT,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE RESTRICT,
  FOREIGN KEY (ad_group_id) REFERENCES ad_groups(ad_group_id) ON DELETE RESTRICT,
  FOREIGN KEY (source_report_job_id) REFERENCES report_jobs(job_id) ON DELETE SET NULL
);

CREATE TABLE keyword_daily (
  profile_id TEXT NOT NULL,
  report_date TEXT NOT NULL,
  ad_product TEXT NOT NULL,
  campaign_id TEXT NOT NULL,
  ad_group_id TEXT NOT NULL,
  keyword_id TEXT NOT NULL,
  impressions INTEGER NOT NULL DEFAULT 0 CHECK (impressions >= 0),
  clicks INTEGER NOT NULL DEFAULT 0 CHECK (clicks >= 0),
  cost_micros INTEGER NOT NULL DEFAULT 0 CHECK (cost_micros >= 0),
  purchases INTEGER NOT NULL DEFAULT 0 CHECK (purchases >= 0),
  units_sold INTEGER NOT NULL DEFAULT 0 CHECK (units_sold >= 0),
  sales_micros INTEGER NOT NULL DEFAULT 0 CHECK (sales_micros >= 0),
  purchases_same_sku INTEGER CHECK (purchases_same_sku IS NULL OR purchases_same_sku >= 0),
  units_sold_same_sku INTEGER CHECK (units_sold_same_sku IS NULL OR units_sold_same_sku >= 0),
  sales_same_sku_micros INTEGER CHECK (sales_same_sku_micros IS NULL OR sales_same_sku_micros >= 0),
  metrics_json TEXT,
  source_report_job_id TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (profile_id, report_date, ad_product, keyword_id),
  FOREIGN KEY (profile_id) REFERENCES amazon_profiles(profile_id) ON DELETE RESTRICT,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE RESTRICT,
  FOREIGN KEY (ad_group_id) REFERENCES ad_groups(ad_group_id) ON DELETE RESTRICT,
  FOREIGN KEY (keyword_id) REFERENCES keywords(keyword_id) ON DELETE RESTRICT,
  FOREIGN KEY (source_report_job_id) REFERENCES report_jobs(job_id) ON DELETE SET NULL
);

CREATE TABLE target_daily (
  profile_id TEXT NOT NULL,
  report_date TEXT NOT NULL,
  ad_product TEXT NOT NULL,
  campaign_id TEXT NOT NULL,
  ad_group_id TEXT NOT NULL,
  target_id TEXT NOT NULL,
  impressions INTEGER NOT NULL DEFAULT 0 CHECK (impressions >= 0),
  clicks INTEGER NOT NULL DEFAULT 0 CHECK (clicks >= 0),
  cost_micros INTEGER NOT NULL DEFAULT 0 CHECK (cost_micros >= 0),
  purchases INTEGER NOT NULL DEFAULT 0 CHECK (purchases >= 0),
  units_sold INTEGER NOT NULL DEFAULT 0 CHECK (units_sold >= 0),
  sales_micros INTEGER NOT NULL DEFAULT 0 CHECK (sales_micros >= 0),
  metrics_json TEXT,
  source_report_job_id TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (profile_id, report_date, ad_product, target_id),
  FOREIGN KEY (profile_id) REFERENCES amazon_profiles(profile_id) ON DELETE RESTRICT,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE RESTRICT,
  FOREIGN KEY (ad_group_id) REFERENCES ad_groups(ad_group_id) ON DELETE RESTRICT,
  FOREIGN KEY (target_id) REFERENCES targets(target_id) ON DELETE RESTRICT,
  FOREIGN KEY (source_report_job_id) REFERENCES report_jobs(job_id) ON DELETE SET NULL
);

CREATE TABLE search_term_daily (
  row_key TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  report_date TEXT NOT NULL,
  ad_product TEXT NOT NULL,
  campaign_id TEXT NOT NULL,
  ad_group_id TEXT NOT NULL,
  keyword_id TEXT,
  target_id TEXT,
  search_term TEXT NOT NULL,
  normalized_search_term TEXT NOT NULL,
  match_type TEXT,
  impressions INTEGER NOT NULL DEFAULT 0 CHECK (impressions >= 0),
  clicks INTEGER NOT NULL DEFAULT 0 CHECK (clicks >= 0),
  cost_micros INTEGER NOT NULL DEFAULT 0 CHECK (cost_micros >= 0),
  purchases INTEGER NOT NULL DEFAULT 0 CHECK (purchases >= 0),
  units_sold INTEGER NOT NULL DEFAULT 0 CHECK (units_sold >= 0),
  sales_micros INTEGER NOT NULL DEFAULT 0 CHECK (sales_micros >= 0),
  metrics_json TEXT,
  source_report_job_id TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (profile_id) REFERENCES amazon_profiles(profile_id) ON DELETE RESTRICT,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE RESTRICT,
  FOREIGN KEY (ad_group_id) REFERENCES ad_groups(ad_group_id) ON DELETE RESTRICT,
  FOREIGN KEY (keyword_id) REFERENCES keywords(keyword_id) ON DELETE SET NULL,
  FOREIGN KEY (target_id) REFERENCES targets(target_id) ON DELETE SET NULL,
  FOREIGN KEY (source_report_job_id) REFERENCES report_jobs(job_id) ON DELETE SET NULL
);

CREATE TABLE advertised_product_daily (
  row_key TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  report_date TEXT NOT NULL,
  ad_product TEXT NOT NULL,
  campaign_id TEXT,
  ad_group_id TEXT,
  advertised_asin TEXT,
  advertised_sku TEXT,
  impressions INTEGER NOT NULL DEFAULT 0 CHECK (impressions >= 0),
  clicks INTEGER NOT NULL DEFAULT 0 CHECK (clicks >= 0),
  cost_micros INTEGER NOT NULL DEFAULT 0 CHECK (cost_micros >= 0),
  purchases INTEGER NOT NULL DEFAULT 0 CHECK (purchases >= 0),
  units_sold INTEGER NOT NULL DEFAULT 0 CHECK (units_sold >= 0),
  sales_micros INTEGER NOT NULL DEFAULT 0 CHECK (sales_micros >= 0),
  metrics_json TEXT,
  source_report_job_id TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (profile_id) REFERENCES amazon_profiles(profile_id) ON DELETE RESTRICT,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE SET NULL,
  FOREIGN KEY (ad_group_id) REFERENCES ad_groups(ad_group_id) ON DELETE SET NULL,
  FOREIGN KEY (source_report_job_id) REFERENCES report_jobs(job_id) ON DELETE SET NULL
);

CREATE TABLE purchased_product_daily (
  row_key TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  report_date TEXT NOT NULL,
  ad_product TEXT NOT NULL,
  campaign_id TEXT,
  ad_group_id TEXT,
  advertised_asin TEXT,
  purchased_asin TEXT NOT NULL,
  purchases INTEGER NOT NULL DEFAULT 0 CHECK (purchases >= 0),
  units_sold INTEGER NOT NULL DEFAULT 0 CHECK (units_sold >= 0),
  sales_micros INTEGER NOT NULL DEFAULT 0 CHECK (sales_micros >= 0),
  metrics_json TEXT,
  source_report_job_id TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (profile_id) REFERENCES amazon_profiles(profile_id) ON DELETE RESTRICT,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE SET NULL,
  FOREIGN KEY (ad_group_id) REFERENCES ad_groups(ad_group_id) ON DELETE SET NULL,
  FOREIGN KEY (source_report_job_id) REFERENCES report_jobs(job_id) ON DELETE SET NULL
);

CREATE TABLE placement_daily (
  row_key TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  report_date TEXT NOT NULL,
  ad_product TEXT NOT NULL,
  campaign_id TEXT NOT NULL,
  placement TEXT NOT NULL,
  impressions INTEGER NOT NULL DEFAULT 0 CHECK (impressions >= 0),
  clicks INTEGER NOT NULL DEFAULT 0 CHECK (clicks >= 0),
  cost_micros INTEGER NOT NULL DEFAULT 0 CHECK (cost_micros >= 0),
  purchases INTEGER NOT NULL DEFAULT 0 CHECK (purchases >= 0),
  units_sold INTEGER NOT NULL DEFAULT 0 CHECK (units_sold >= 0),
  sales_micros INTEGER NOT NULL DEFAULT 0 CHECK (sales_micros >= 0),
  metrics_json TEXT,
  source_report_job_id TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (profile_id) REFERENCES amazon_profiles(profile_id) ON DELETE RESTRICT,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE RESTRICT,
  FOREIGN KEY (source_report_job_id) REFERENCES report_jobs(job_id) ON DELETE SET NULL
);

PRAGMA optimize;
